---
# tasks file for centos

- name: Add Mongodb repository
  yum_repository:
    name: mongodb
    description: 'Mongodb official repository'
    baseurl: "{{ repository_url }}"
    gpgcheck: 1
    enabled: 1
    gpgkey: "{{ gpg_key_url }}"
