---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mongod_debian_1
    image: dramaturg/debian-systemd
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    expose: 27017
  - name: mongod_debian_2
    image: dramaturg/debian-systemd
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    expose: 27017
  - name: mongod_debian_3
    image: dramaturg/debian-systemd
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    expose: 27017
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    vv: true
scenario:
  name: mongodb_debian
verifier:
  name: testinfra
  lint:
    name: flake8
